### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by MisterAwesome23** [arduino-libraries/Mouse#16]
This library has no examples included, but-
https://www.arduino.cc/reference/en/language/functions/usb/mouse/
already has three basic example:

- KeyboardAndMouseControl
- ButtonMouseControl
- JoystickMouseControl

Should I just migrate them here and create a pull request or what should be done?

**Comment by per1234** [comment]
We already have pull requests for that:
- KeyboardAndMouseControl: https://github.com/arduino-libraries/Mouse/pull/15
- ButtonMouseControl: https://github.com/arduino-libraries/Mouse/pull/13
- JoystickMouseControl: https://github.com/arduino-libraries/Mouse/pull/12
