### ISSUE TITLE
Platform IO, Teensy, HID.h

### ISSUE THREAD

**Issue by ThirtySomething** [arduino-libraries/Mouse#21]
Hi there,

long time ago I've wrote a small program to emulate a mouse button click for clicker games. This was done for a [Teensy 2.0](https://www.pjrc.com/store/teensy.html) using the Arduino IDE - see [here](https://github.com/ThirtySomething/ClickerFraud) for more details.

Now I've got a new computer and tried to get this program compiling again. I'm using Platform IO in VS Code as extension. An empty default program without any logic compiles well. When I add the mouse library, the compile fails because the header file `HID.h` used in `Mouse.h` is not found.

So I tried this also in the Arduino IDE - same happens there, the header file `HID.h` is missing.

Seems that there is something missing, but I cannot remember on what this lib depends. Same also for Keyboard, there is also `HID.h` used. Also can't find any hint on the pages of Arduino for [keyboard](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/) or [mouse](https://www.arduino.cc/reference/en/language/functions/usb/mouse/).

What have i missed?

**Comment by per1234** [comment]
Hi @ThirtySomething. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/

**Comment by PaulStoffregen** [comment]
If using Teensy, click Tools > USB Type to set it to one of the options that implements USB mouse.

If that doesn't solve it, the PJRC forum is the proper place to ask for help with Teensy.
https://forum.pjrc.com/forums/3-Technical-Support-amp-Questions

**Comment by ThirtySomething** [comment]
I figured out the problem. First of all I need to install Arduino IDE 1.8.11 - Teensyduino is not compatible with newer versions. Then I have to install [Teensyduino ](https://www.pjrc.com/teensy/teensyduino.html) to make the environment compatible for the board. After that I need to setup the board as USB mouse as @PaulStoffregen proposed. Then I'm able to compile. I will also figure out how to do this with platform.io. Thanks for hints and pointing me to the right direction.

**Comment by ThirtySomething** [comment]
For platform.io I need to add `build_flags = -D USB_RAWHID` to the configuration file `platformio.ini` as described [here](https://docs.platformio.org/en/latest/platforms/teensy.html#usb-features). Then I adapted the example files from the [Teensy page](https://www.pjrc.com/teensy/usb_mouse.html) and now it works.

**Comment by PaulStoffregen** [comment]
> Teensyduino is not compatible with newer versions

You must have an old installer, downloaded to your PC in the days when 1.8.11 was the most recent version of Arduino.

**Comment by ThirtySomething** [comment]
> You must have an old installer, downloaded to your PC in the days when 1.8.11 was the most recent version of Arduino.

Correct - during my tests there was a note on the Teensy page [here](https://www.pjrc.com/teensy/td_download.html) that the latest compatible version was 1.8.11. Now it's changed and up to 1.8.13.
